manage acceptance of remote agents
Signed-off-by: Sheldon Regular <sheldon.regular@gmail.com>

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -2,7 +2,9 @@
 # set -x
 
 # Set of valid agents - add new agents here
+# added remote as a valid agent to allow for remote agent testing.
 export VALID_AGENTS=$(ls aries-backchannels/*/Dockerfile.* | sed "s/^.*file.//" |  tr "\n" " " | sort -u)
+VALID_AGENTS="${VALID_AGENTS} remote"
 
 export MSYS_NO_PATHCONV=1
 # getDockerHost; for details refer to https://github.com/bcgov/DITP-DevOps/tree/main/code/snippets#getdockerhost
@@ -33,6 +35,15 @@ TAILS_SERVER_URL_INTERNAL="$(echo ${TAILS_SERVER_URL_INTERNAL} | sed "s/:\/\/loc
 
 REDIS_CLUSTER_URL_HOST="${REDIS_CLUSTER_URL_CONFIG:-http://localhost:6377}"
 
+# Define variables for endpoints and ports
+declare ACME_ENDPOINT=""
+declare ACME_PORT=""
+declare BOB_ENDPOINT=""
+declare BOB_PORT=""
+declare FABER_ENDPOINT=""
+declare FABER_PORT=""
+declare MALLORY_ENDPOINT=""
+declare MALLORY_PORT=""
 
 # Running on Windows?
 if [[ "$OSTYPE" == "msys" ]]; then
@@ -823,20 +834,36 @@ startHarness(){
 
   # Only start agents that are asked for in the ./manage start command
   if [[ "$ACME" != "none" ]]; then
-    export ACME_AGENT=${ACME_AGENT:-${ACME}-agent-backchannel}
-    startAgent Acme acme_agent "$ACME_AGENT" "9020-9029" 9020 9021 "$AIP_CONFIG" "$ACME"
+    if checkAndSetRemote "ACME"; then
+      echo "ACME is set to remote."
+    else
+      export ACME_AGENT=${ACME_AGENT:-${ACME}-agent-backchannel}
+      startAgent Acme acme_agent "$ACME_AGENT" "9020-9029" 9020 9021 "$AIP_CONFIG" "$ACME"
+    fi
   fi
   if [[ "$BOB" != "none" ]]; then
-    export BOB_AGENT=${BOB_AGENT:-${BOB}-agent-backchannel}
-    startAgent Bob bob_agent "$BOB_AGENT" "9030-9039" 9030 9031 "$AIP_CONFIG" "$BOB"
+    if checkAndSetRemote "BOB"; then
+      echo "BOB is set to remote."
+    else
+      export BOB_AGENT=${BOB_AGENT:-${BOB}-agent-backchannel}
+      startAgent Bob bob_agent "$BOB_AGENT" "9030-9039" 9030 9031 "$AIP_CONFIG" "$BOB"
+    fi
   fi
   if [[ "$FABER" != "none" ]]; then
-    export FABER_AGENT=${FABER_AGENT:-${FABER}-agent-backchannel}
-    startAgent Faber faber_agent "$FABER_AGENT" "9040-9049" 9040 9041 "$AIP_CONFIG" "$FABER"
+    if checkAndSetRemote "FABER"; then
+      echo "FABER is set to remote."
+    else
+      export FABER_AGENT=${FABER_AGENT:-${FABER}-agent-backchannel}
+      startAgent Faber faber_agent "$FABER_AGENT" "9040-9049" 9040 9041 "$AIP_CONFIG" "$FABER"
+    fi
   fi
   if [[ "$MALLORY" != "none" ]]; then
-    export MALLORY_AGENT=${MALLORY_AGENT:-${MALLORY}-agent-backchannel}
-    startAgent Mallory mallory_agent "$MALLORY_AGENT" "9050-9059" 9050 9051 "$AIP_CONFIG" "$MALLORY"
+    if checkAndSetRemote "MALLORY"; then
+      echo "MALLORY is set to remote."
+    else
+      export MALLORY_AGENT=${MALLORY_AGENT:-${MALLORY}-agent-backchannel}
+      startAgent Mallory mallory_agent "$MALLORY_AGENT" "9050-9059" 9050 9051 "$AIP_CONFIG" "$MALLORY"
+    fi
   fi
 
   echo
@@ -863,6 +890,22 @@ startHarness(){
   if [[ "${REPORT}" = "allure" ]]; then
     writeEnvProperties
   fi
+}
+
+# Check if the agent is remote and set the endpoint and port
+checkAndSetRemote() {
+  local agent_name=$1
+  local endpoint_var="${agent_name}_ENDPOINT"
+  local port_var="${agent_name}_PORT"
+
+  if [[ "${!agent_name}" == "remote" ]]; then
+    if [[ -z "${!endpoint_var}" || -z "${!port_var}" ]]; then
+      echo "Error: ${agent_name} is set to remote, but ${endpoint_var} or ${port_var} is not set."
+      exit 1
+    fi
+    return 0
+  fi
+  return 1
 }
 
 deleteAgents() {
@@ -960,6 +1003,41 @@ runRunSet() {
   exit 0
 }
 
+# Function to build the -D options for agents when running the tests
+buildAgentOptions() {
+  local agent_name=$1
+  local endpoint_var="${agent_name}_ENDPOINT"
+  local port_var="${agent_name}_PORT"
+
+  if [[ "${!agent_name}" == "remote" ]]; then
+    if [[ -z "${!endpoint_var}" || -z "${!port_var}" ]]; then
+      echo "Error: ${agent_name} is set to remote, but ${endpoint_var} or ${port_var} is not set."
+      exit 1
+    fi
+    echo "-D ${agent_name}=${!endpoint_var}:${!port_var}"
+  else
+    # Use predefined ports for non-remote agents
+    case ${agent_name} in
+      ACME)
+        echo "-D ${agent_name}=http://0.0.0.0:9020"
+        ;;
+      BOB)
+        echo "-D ${agent_name}=http://0.0.0.0:9030"
+        ;;
+      FABER)
+        echo "-D ${agent_name}=http://0.0.0.0:9040"
+        ;;
+      MALLORY)
+        echo "-D ${agent_name}=http://0.0.0.0:9050"
+        ;;
+      *)
+        echo "Error: Unknown agent ${agent_name}"
+        exit 1
+        ;;
+    esac
+  fi
+}
+
 runTests() {
   runArgs=${@}
 
@@ -977,14 +1055,20 @@ runTests() {
   export BEHAVE_INI_TMP="$(pwd)/behave.ini.tmp"
   cp ${BEHAVE_INI} ${BEHAVE_INI_TMP}
 
+  # Build the agent options
+  ACME_OPTIONS=$(buildAgentOptions "ACME")
+  BOB_OPTIONS=$(buildAgentOptions "BOB")
+  FABER_OPTIONS=$(buildAgentOptions "FABER")
+  MALLORY_OPTIONS=$(buildAgentOptions "MALLORY")
+
   if [[ "${REPORT}" = "allure" && "${COMMAND}" != "dry-run" ]]; then
       echo "Executing tests with Allure Reports."
-      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini -v "$(pwd)/.logs:/aries-test-harness/logs" -v "$(pwd)/aries-test-harness/allure/allure-results:/aries-test-harness/allure/allure-results/" $DOCKER_ENV aries-test-harness -k ${runArgs} -f allure_behave.formatter:AllureFormatter -o ./allure/allure-results -f progress -D Acme=http://0.0.0.0:9020 -D Bob=http://0.0.0.0:9030 -D Faber=http://0.0.0.0:9040 -D Mallory=http://0.0.0.0:9050
+      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini -v "$(pwd)/.logs:/aries-test-harness/logs" -v "$(pwd)/aries-test-harness/allure/allure-results:/aries-test-harness/allure/allure-results/" $DOCKER_ENV aries-test-harness -k ${runArgs} -f allure_behave.formatter:AllureFormatter -o ./allure/allure-results -f progress ${ACME_OPTIONS} ${BOB_OPTIONS} ${FABER_OPTIONS} ${MALLORY_OPTIONS}
   elif [[ "${COMMAND}" = "dry-run" ]]; then
-      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini $DOCKER_ENV aries-test-harness -k ${runArgs} -D Acme=http://0.0.0.0:9020 -D Bob=http://0.0.0.0:9030 -D Faber=http://0.0.0.0:9040 -D Mallory=http://0.0.0.0:9050 |\
+      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini $DOCKER_ENV aries-test-harness -k ${runArgs} ${ACME_OPTIONS} ${BOB_OPTIONS} ${FABER_OPTIONS} ${MALLORY_OPTIONS} |\
         grep "Feature:\|Scenario Outline\|\@" | sed "/n(u/d"
   else
-      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini -v "$(pwd)/.logs:/aries-test-harness/logs" $DOCKER_ENV aries-test-harness -k ${runArgs} -D Acme=http://0.0.0.0:9020 -D Bob=http://0.0.0.0:9030 -D Faber=http://0.0.0.0:9040 -D Mallory=http://0.0.0.0:9050
+      ${terminalEmu} docker run ${INTERACTIVE} --rm --network="host" -v ${BEHAVE_INI_TMP}:/aries-test-harness/behave.ini -v "$(pwd)/.logs:/aries-test-harness/logs" $DOCKER_ENV aries-test-harness -k ${runArgs} ${ACME_OPTIONS} ${BOB_OPTIONS} ${FABER_OPTIONS} ${MALLORY_OPTIONS}
   fi
   local docker_result=$?
   rm ${BEHAVE_INI_TMP}
@@ -1068,6 +1152,7 @@ isAgent() {
   for agent in ${VALID_AGENTS}; do
     if [[ "${1}" == "${agent}" ]]; then
         result=true
+        break
     fi
   done
 
@@ -1154,6 +1239,68 @@ if [[ "${COMMAND}" == "run" || "${COMMAND}" == "start" || "${COMMAND}" == "test"
   TAGS=""
   BEHAVE_INI=aries-test-harness/behave.ini
 
+  # Parse long options
+  TEMP_ARGS=()
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+      --aep)
+        ACME_ENDPOINT="$2"
+        shift 2
+        ;;
+      --ap)
+        ACME_PORT="$2"
+        shift 2
+        ;;
+      --bep)
+        BOB_ENDPOINT="$2"
+        shift 2
+        ;;
+      --bp)
+        BOB_PORT="$2"
+        shift 2
+        ;;
+      --fep)
+        FABER_ENDPOINT="$2"
+        shift 2
+        ;;
+      --fp)
+        FABER_PORT="$2"
+        shift 2
+        ;;
+      --mep)
+        MALLORY_ENDPOINT="$2"
+        shift 2
+        ;;
+      --mp)
+        MALLORY_PORT="$2"
+        shift 2
+        ;;
+      --)
+        shift
+        break
+        ;;
+      -*)
+        echo -e \\n"Invalid script option: $1"\\n
+        usage
+        ;;
+      *)
+        TEMP_ARGS+=("$1")
+        shift
+        ;;
+    esac
+  done
+
+  # Add remaining arguments to TEMP_ARGS
+  while [[ $# -gt 0 ]]; do
+    TEMP_ARGS+=("$1")
+    shift
+  done
+
+  # Rebuild the argument list to exclude long options
+  set -- "${TEMP_ARGS[@]}"
+
+  # Parse short options
+  OPTIND=1  # Reset OPTIND to 1 to reprocess the arguments
   while getopts "hna:b:c:f:m:r:e:d:t:v:i:" FLAG; do
     case $FLAG in
         h ) usage ;;
